logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fanglv_tfdd_v_2.0?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: chenxing
