logging:
  config: classpath:log4j2-dev.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bbt?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root

